# start the environment of online judge
.PHONY: start
start:
	docker-compose up -d

# stop the environment of online judge
.PHONY: stop
stop:
	docker-compose down

# run the submission
.PHONY: user
user:
	go build -o judgement ./app/judgement/cmd/main.go

# run the monolithic main function
.PHONY: main
main:
	go build -o online-judge main.go

# download the required dependencies
.PHONY: mod
mod:
	go mod tidy


# delete all of the binary files that generated by makefile
.PHONY: clear
clear:
	rm judgement
	rm online-judge

.PHONY: all
all: mod user main