// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Eutop1a",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/problem/create": {
            "post": {
                "description": "创建新题目接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json",
                    "multipart/form-data"
                ],
                "tags": [
                    "Admin API"
                ],
                "summary": "创建新题目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目内容",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目难度",
                        "name": "difficulty",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "时间限制",
                        "name": "max_runtime",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "内存限制",
                        "name": "max_memory",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "测试样例集",
                        "name": "test_cases",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1014 服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.CreateProblemResponse"
                        }
                    }
                }
            }
        },
        "/admin/problem/file/create": {
            "post": {
                "description": "创建新题目接口，输入输出是文件的形式",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin API"
                ],
                "summary": "创建新题目，输入输出是文件的形式",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目内容",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目难度",
                        "name": "difficulty",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "时间限制",
                        "name": "max_runtime",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "内存限制",
                        "name": "max_memory",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "multi",
                        "description": "问题的输入文件(.in)",
                        "name": "input",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "multi",
                        "description": "问题的输出文件(.out)",
                        "name": "expected",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1014 服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.CreateProblemResponse"
                        }
                    }
                }
            }
        },
        "/admin/problem/file/update": {
            "put": {
                "description": "更新题目信息接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin API"
                ],
                "summary": "更新题目信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目ID",
                        "name": "problem_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目标题",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "题目内容",
                        "name": "content",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "题目难度",
                        "name": "difficulty",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "时间限制",
                        "name": "max_runtime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "内存限制",
                        "name": "max_memory",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "multi",
                        "description": "问题的输入文件(.in)",
                        "name": "input",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "multi",
                        "description": "问题的输出文件(.out)",
                        "name": "expected",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProblemResponse"
                        }
                    }
                }
            }
        },
        "/admin/problem/file/{problem_id}": {
            "delete": {
                "description": "删除题目接口，输入输出是文件的形式",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin API"
                ],
                "summary": "删除题目，输入输出是文件的形式",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目ID",
                        "name": "problem_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteProblemResponse"
                        }
                    }
                }
            }
        },
        "/admin/problem/{problem_id}": {
            "put": {
                "description": "更新题目信息接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin API"
                ],
                "summary": "更新题目信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目ID",
                        "name": "problem_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目标题",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "题目内容",
                        "name": "content",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "题目难度",
                        "name": "difficulty",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "时间限制",
                        "name": "max_runtime",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "内存限制",
                        "name": "max_memory",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "测试样例集",
                        "name": "test_cases",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProblemResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除题目接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin API"
                ],
                "summary": "删除题目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目ID",
                        "name": "problem_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteProblemResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/add-admin": {
            "post": {
                "description": "添加管理员接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin API"
                ],
                "summary": "添加管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.AddAdminResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/add-super-admin": {
            "post": {
                "description": "添加超级管理员接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin API"
                ],
                "summary": "添加超级管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密钥",
                        "name": "secret",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.AddSuperAdminResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{user_id}": {
            "delete": {
                "description": "删除用户接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin API"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteUserResponse"
                        }
                    }
                }
            }
        },
        "/check-picture-code": {
            "post": {
                "description": "检查图片验证码",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verification Code API"
                ],
                "summary": "检查图片验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "图片验证码",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户名不存在",
                        "schema": {
                            "$ref": "#/definitions/models.CheckPictureCodeResponse"
                        }
                    }
                }
            }
        },
        "/leaderboard/user": {
            "get": {
                "description": "获取用户题解排名接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rank API"
                ],
                "summary": "获取用户题解排名",
                "responses": {
                    "200": {
                        "description": "1014 服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.GetUserLeaderboardResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用户登录接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json",
                    "text/xml"
                ],
                "tags": [
                    "User API"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    }
                }
            }
        },
        "/problem/id": {
            "post": {
                "description": "获取题目ID接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Problem API"
                ],
                "summary": "获取题目ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1008 需要登录",
                        "schema": {
                            "$ref": "#/definitions/models.GetProblemIDResponse"
                        }
                    }
                }
            }
        },
        "/problem/list": {
            "get": {
                "description": "获取题目列表接口",
                "tags": [
                    "Problem API"
                ],
                "summary": "获取题目列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "input current page num, default: 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.GetProblemListResponse"
                        }
                    }
                }
            }
        },
        "/problem/random": {
            "get": {
                "description": "随机获取一个题目接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json",
                    "multipart/form-data"
                ],
                "tags": [
                    "Problem API"
                ],
                "summary": "随机获取一个题目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1008 需要登录",
                        "schema": {
                            "$ref": "#/definitions/models.GetProblemRandomResponse"
                        }
                    }
                }
            }
        },
        "/problem/{problem_id}": {
            "get": {
                "description": "获取单个题目详细接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json",
                    "multipart/form-data"
                ],
                "tags": [
                    "Problem API"
                ],
                "summary": "获取单个题目详细",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目ID",
                        "name": "problem_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1021 题目ID不存在",
                        "schema": {
                            "$ref": "#/definitions/models.GetProblemDetailResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "用户注册接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json",
                    "multipart/form-data"
                ],
                "tags": [
                    "User API"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.RegisterResponse"
                        }
                    }
                }
            }
        },
        "/send-email-code": {
            "post": {
                "description": "发送邮箱验证码接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verification Code API"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.SendEmailCodeResponse"
                        }
                    }
                }
            }
        },
        "/send-picture-code": {
            "post": {
                "description": "发送图片验证码接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verification Code API"
                ],
                "summary": "发送图片验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1014 服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.SendPictureCodeResponse"
                        }
                    }
                }
            }
        },
        "/submissions/code": {
            "post": {
                "description": "提交代码接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Submission API"
                ],
                "summary": "提交代码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目id",
                        "name": "problem_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "language",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代码",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.SubmitCodeResponse"
                        }
                    }
                }
            }
        },
        "/submissions/file/code": {
            "post": {
                "description": "提交代码接口(文件)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Submission API"
                ],
                "summary": "提交代码(文件)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题目id",
                        "name": "problem_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "language",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "代码",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.SubmitCodeResponse"
                        }
                    }
                }
            }
        },
        "/user-id": {
            "post": {
                "description": "获取用户ID接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User API"
                ],
                "summary": "获取用户ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户名不存在",
                        "schema": {
                            "$ref": "#/definitions/models.GetUserIDResponse"
                        }
                    }
                }
            }
        },
        "/users/get": {
            "get": {
                "description": "获取用户详细信息接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User API"
                ],
                "summary": "获取用户详细信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.GetUserDetailResponse"
                        }
                    }
                }
            }
        },
        "/users/update": {
            "put": {
                "description": "更新用户详细信息接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User API"
                ],
                "summary": "更新用户详细信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "用户密码",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "用户邮箱",
                        "name": "email",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "邮箱验证码",
                        "name": "code",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserDetailResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddAdminResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 删除用户成功\" \"1001 参数错误\" \"1005 没有此用户ID\" \"1008 需要登录\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.AddSuperAdminResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 添加超级管理员成功\" \"1001 参数错误\" \"1005 没有此用户ID\" \"1026 用户已是管理员\" \"1025 密钥错误\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.CheckPictureCodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 图片验证码正确\" \"1017 图片验证码错误\" \"1014 用户名不存在\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.CreateProblemResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 创建成功\" \"1001 参数错误\" \"1018 测试用例格式错误\" \"1019 题目标题已存在\" \"1008 需要登录\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.DeleteProblemResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 删除成功\" \"1021 题目ID不存在\" \"1008 需要登录\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {},
                "msg": {}
            }
        },
        "models.DeleteUserResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 删除用户成功\" \"1001 参数错误\" \"1004 没有此用户ID\" \"1008 需要登录\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.GetProblemDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 获取题目列表成功\" \"1008 需要登录\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.GetProblemIDResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 获取题目ID成功\" \"1020 题目title不存在\" \"1008 需要登录\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.GetProblemListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 获取题目列表成功\" \"1008 需要登录\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.GetProblemRandomResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 获取题目ID成功\" \"1008 需要登录\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.GetUserDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 获取用户信息成功\" \"1001 参数错误\" \"1004 没有此用户ID\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.GetUserIDResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 获取用户ID成功\" \"1004 用户名不存在\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.GetUserLeaderboardResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 获取用户题解排名成功\" \"1022 获取用户题解排名失败\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 登录成功\" \"1001 参数错误\" \"1004 用户名不存在\" \"1004 验证码错误\" \"1011 验证码过期\" \"1006 密码错误\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.RegisterResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 注册成功\" \"1002 用户已存在\" \"1011 验证码错误或已过期\" \"1012 验证码过期\" \"1013 该邮箱已经存在\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.SendEmailCodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 发送邮箱验证码成功\" \"1015 邮箱格式错误\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.SendPictureCodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 发送图片验证码成功\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.SubmitCodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 提交代码成功\" \"1005 用户ID不存在\" \"1021 题目ID不存在\" \"1024 不支持的语言类型\" \"1008 需要登录\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        },
        "models.UpdateProblemResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 修改成功\" \"1021 题目ID不存在\" \"1019 题目标题已存在\" \"1018 测试用例格式错误\" \"1008 需要登录\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {},
                "msg": {}
            }
        },
        "models.UpdateUserDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "\"1000 更新用户信息成功\" \"1001 参数错误\" \"1004 没有此用户ID\" \"1011 验证码错误\" \"1012 验证码过期\" \"1014 服务器内部错误\"",
                    "type": "integer"
                },
                "data": {
                    "description": "omitempty 字段为空就忽略"
                },
                "msg": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:65533",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "online-judge",
	Description:      "Refactoring",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
